[pytest]
# testpaths: 指定测试文件搜索的根目录
testpaths = tests

# python_files: 指定测试文件的命名模式
python_files = test_*.py

# python_classes: 指定测试类的命名模式
python_classes = Test*

# python_functions: 指定测试函数的命名模式
python_functions = test_*

# addopts: 添加默认命令行参数，包括指定覆盖率统计的模块、生成 HTML 和终端报告
addopts = --cov=CookingEngine --cov=Ingredient --cov=KitchenBase --cov-report=html --cov-report=term

# filterwarnings: 过滤指定类型的警告，这里忽略 DeprecationWarning
filterwarnings = ignore::DeprecationWarning
