[pytest]
testpaths = tests  # 测试目录
python_files = test_*.py  # 测试文件命名规则
python_classes = Test*    # 测试类命名规则
python_functions = test_* # 测试函数命名规则
addopts = --cov=campsis --cov-report=html --cov-report=term  # 覆盖率报告（可选）
filterwarnings = ignore::DeprecationWarning  # 忽略无关警告